---
title: "Week 2 Lecture"
author: "Leo Qi Jie, Justin"
date: "2024-01-24"
output: 
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6
   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
stock_df = readRDS("data/wk2_stocks.rds")
str(stock_df)
```
```{r}
#Question 1 The cumulative returns of the S&P index during this period is ________.

sum(stock_df$SPY_returns) * 100

```
The cumulative returns of the S&P index during this period is `r sum(stock_df$SPY_returns) * 100`.


```{r}
#Question 2 The average daily returns of the S&P index during this period is ________.

mean(stock_df$SPY_returns)

```
The average daily returns of the S&P index during this period is `r mean(stock_df$SPY_returns)`.

```{r}
#Question 3 The standard deviation of the daily returns of the S&P index during this period is ________.

sd(stock_df$SPY_returns)
```
The standard deviation of the daily returns of the S&P index during this period is `r sd(stock_df$SPY_returns)`.

```{r}
#Question 4 Create a plot that shows the prices of S&P in this period.

stock_df %>%
  ggplot(aes(x = date, y = SPY_prices)) +
  geom_line()

# stock_df %>%
#   plot_ly(x = ~date,y = ~SPY_prices,type = "scatter", mode = "lines") 
  

```

```{r}
#Question 5 Create a plot that shows the total yearly returns of S&P from 2001 to 2023.

stock_df %>%
  mutate(year = year(date))%>%
  group_by(year) %>%
  summarize(yr_return = sum(SPY_returns)*100) %>%
  ggplot(aes(x = year, y = yr_return)) +
  geom_col()
  
```

